pipeline {
    agent any    
     options {
        // This is required if you want to clean before build
        skipDefaultCheckout(true)
    }
    stages {
        stage('Cleanup'){
            steps {
                // Clean before build
                cleanWs()
            }
        }
        stage('Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/AVSLDOT/goat-book.git'                
            }
        }
        stage('Build') {
            steps {
                sh 'docker build -t superlists .'
            }
        }        
        
    }
}

